INSERT INTO forum_topic (id, topic, description) VALUES ('1', 'food', 'Reprehenderit ea ratione est architecto et nostrum. Molestiae hic veritatis et enim deserunt. Fugit ut est exercitationem omnis et.');
INSERT INTO forum_topic (id, topic, description) VALUES ('2', 'health', 'Ducimus laudantium aut et cum. Eius atque expedita labore cupiditate. Est quas quidem iusto possimus et animi. Est distinctio optio iusto amet est dolorum repellendus.');
INSERT INTO forum_topic (id, topic, description) VALUES ('3', 'toys', 'Aliquam aut cum sit est. Corrupti voluptatem neque at fugiat numquam. Nisi velit praesentium minus non. Dolor et nemo consequatur.');
INSERT INTO forum_topic (id, topic, description) VALUES ('4', 'vet', 'Non voluptatum et eum eveniet minus dolor quis ipsum. Quam natus illo dolorem.');
INSERT INTO forum_topic (id, topic, description) VALUES ('5', 'behaviour', 'Soluta quia commodi quisquam impedit. Voluptas sint est sed unde quod. Sed recusandae sit velit velit.');
INSERT INTO forum_topic (id, topic, description) VALUES ('6', 'meet my cat', 'Aut eveniet quasi a. Sapiente pariatur velit deleniti eaque praesentium. Ut quasi nisi quos.');
INSERT INTO forum_topic (id, topic, description) VALUES ('7', 'accessories', 'Est explicabo eum vitae sequi distinctio quia et. Autem delectus voluptas nisi ut. Nam aut ut placeat suscipit ullam ut. Perferendis ratione perspiciatis aut es');
INSERT INTO forum_topic (id, topic, description) VALUES ('8', 'pet shop', 'Et fuga doloremque minus nam ipsam voluptas. Enim esse porro magnam vero praesentium totam et dolorum.');
INSERT INTO forum_topic (id, topic, description) VALUES ('9', 'grooming', 'Laborum quibusdam velit aut. Ut aut animi ratione sit. Quo voluptatem vitae rerum ipsa.');
INSERT INTO forum_topic (id, topic, description) VALUES ('10', 'first time owner', 'Voluptates natus sit eum maxime. Repellat quis exercitationem dolor nobis dignissimos voluptate quisquam sunt. Dicta repellendus dolor vel saepe rem qui voluptatibus et.');

--DROP TABLE IF EXISTS `forum_thread`;

-- CREATE TABLE forum_thread (
--   id SERIAL primary key,
--   thread VARCHAR(90),
--   CONSTRAINT FK_forum_topic_id FOREIGN KEY (topic_id) REFERENCES forum_topic(id),
--   content TEXT,
--   CONSTRAINT FK_forum_user_id FOREIGN KEY (creator_id) REFERENCES forum_user(id),
--   created TIMESTAMP NOT NULL DEFAULT now()
-- );

INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('1', '1', 'Animi quas quidem aut in magnam.', 'Explicabo soluta et sint sed cupiditate possimus qui ad. Et ut voluptatem et temporibus cum. Iusto aut voluptas cum minima ea quibusdam delectus.', '1977-09-23 01:26:18', '1');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('2', '2', 'Voluptate autem nemo accusamus quis.', 'Voluptatum quibusdam enim qui molestiae in. Velit sed unde exercitationem voluptas vel voluptatum non. Quae ipsa dolor in rem adipisci cum.', '1974-09-27 01:29:55','2');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('3', '3', 'A ipsam dolorum ex hic sit earum dolor temporibus.', 'Facilis vitae tenetur soluta veritatis. Et est aliquam consequatur. Temporibus quaerat perferendis numquam tempora cum velit quidem.', '1980-03-22 07:10:53','3');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('4', '4', 'Asperiores porro id culpa.', 'Aliquam sapiente laborum dolor sed quae aut laudantium. Cum laudantium eligendi ut non minus. Ut et incidunt et aut ex sit. Omnis et recusandae sunt sed vel autem repellat.', '2001-05-23 09:26:50','1');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('5', '5', 'Non eius aut molestias quia voluptatem sit quis.', 'Rem incidunt in harum similique ut. Officia commodi dolorem optio officiis modi voluptatem. Architecto iure consequuntur rerum ex nihil sint enim autem.', '1993-08-10 22:08:42','2');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('6', '6', 'Ut rerum saepe quisquam voluptate.', 'Cupiditate et totam assumenda eaque et tempora. Autem doloremque architecto error qui debitis. Et est nihil non mollitia.', '1988-08-14 21:08:34','3');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('7', '3', 'Rerum consequatur nam veritatis ut.', 'Vero accusamus dicta occaecati ullam non at aut. Iste porro et enim blanditiis nostrum et minus. Nesciunt atque molestiae quisquam.', '2008-10-18 01:20:49','1');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('8', '7', 'Cum voluptas delectus itaque architecto ut sint.', 'Delectus quisquam sed velit et non optio temporibus. Rerum vel vel molestiae qui dolor quia. Sint ut optio illum aut voluptatem delectus.', '2022-02-03 11:53:26','2');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('9', '8', 'Laborum est dolorem dolorem maiores dolore sequi.', 'Debitis iure esse molestias quis. Ut dolorum illo aut est dolorem. Inventore dolor quae sint est. Voluptatibus incidunt consectetur laborum ex harum totam.', '1999-07-10 18:27:06','3');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('10', '9', 'Voluptatem veniam aut sed et praesentium id sequi.', 'Ut dolorem iusto voluptas sed. Dolores voluptas velit quis quas. Consequatur tenetur velit quia quis rerum autem.', '2017-05-02 15:30:36','1');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('11', '2', 'Aliquid quo quia optio qui accusamus officia necessitatibus.', 'Ut voluptatibus et vitae sint ducimus. Eaque consequatur possimus nemo ut. Est et debitis sequi vel consequatur.', '2001-11-15 22:24:36','2');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('12', '10', 'Perspiciatis ipsum et nihil eveniet.', 'Voluptas aut in eligendi. Fugiat ratione delectus natus inventore. Similique eveniet hic praesentium sit qui eum facere.', '1970-10-14 11:13:10','3');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('13', '6', 'Sed et eius eum odio.', 'Voluptas et placeat', '1983-08-11 02:35:05','1');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('14', '3', 'At dolorem error illum assumenda repellendus ut.', 'Sit iusto aperiam odio et sapiente est officiis. Ut ut quos est. Vel sunt sit aliquam quidem dolorem voluptas.', '2003-05-08 12:37:21','1');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('15', '4', 'Necessitatibus consectetur quod qui.', 'Qui dolor sit vero voluptatum. Quaerat voluptatem cumque molestiae ad id quae. Eaque natus dolorem et nostrum fugit possimus dolore. Voluptatem excepturi et in at et odit reprehenderit.', '1971-01-31 20:25:45', '2');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('17', '5', 'Aut necessitatibus id laborum eum enim nulla.', 'Suscipit error molestiae possimus a sequi. Suscipit amet fugiat et maiores unde. Suscipit soluta cupiditate rerum aut vel.', '2017-09-01 08:57:42','3');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('17', '3', 'Quisquam sapiente modi aperiam numquam perferendis magnam.', 'Laborum et recusandae est sed fuga eligendi. Fuga et id explicabo velit sapiente nihil officia. Tempora autem vitae nostrum eos. Voluptatem est sit quia quidem tempora est.', '2003-09-08 11:36:30','1');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('18', '1', 'Et autem nulla nobis et.', 'Et architecto cupiditate adipisci earum. Minima voluptatibus praesentium amet quibusdam nihil. Aut quasi repudiandae nostrum est velit dolorem. Sunt dolorum fuga est qui ipsam soluta porro deleniti.', '1976-04-14 12:42:30','2');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('19', '4', 'Nulla nisi quia quos fugiat.', 'Id esse unde amet nam sint et. Aut nisi reprehenderit non quos voluptatem aut. Alias tempore voluptas vitae doloremque magnam ipsam illo est. Illo iusto odit et quisquam molestias nemo.', '1993-11-17 03:48:22','3');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('20', '2', 'Iusto dolorem corrupti ipsum et.', 'Nobis velit natus ut nostrum. Commodi sed quam porro voluptates. Doloremque corporis velit debitis aliquid recusandae sed sit. Et voluptas quis ut ea et temporibus.', '2006-12-28 07:24:47','1');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('21', '1', 'Quia itaque ducimus sit illo ut provident doloribus explicabo.', 'Quam fugit tempore odit. Ab est dolores voluptatem eum placeat asperiores voluptas. Accusantium ullam voluptas amet.', '1979-06-12 11:38:42','2');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('22', '6', 'Quis vel necessitatibus ut nemo dolorum.', 'Reiciendis beatae aut ipsa qui et asperiores explicabo. Facilis corrupti enim alias et provident veritatis odit. Officiis alias est ea delectus id.', '1977-09-19 06:57:28','3');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('23', '4', 'Ratione quo at ipsa.', 'Aperiam in quia eveniet eos dolorem cupiditate. Est ullam sit atque nihil voluptate magnam tempora. Numquam veritatis occaecati rem ut quas qui ex ab. Similique vitae est aspernatur unde distinctio.', '1989-03-11 23:29:56','1');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('24', '1', 'Perferendis quis quo natus est enim.', 'Nam reprehenderit non id. Sed voluptas nostrum ut cum odio. Consequuntur dignissimos magnam non aspernatur error consequatur. Non commodi rem sed.', '2010-03-03 09:21:11','2');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('25', '6', 'In laudantium numquam a consequatur et occaecati.', 'Veniam neque sunt et. A ullam amet nemo reprehenderit. Harum neque eaque est.', '1993-12-18 10:59:37','3');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('26', '3', 'Dolorum tenetur culpa possimus dolorem quod.', 'Praesentium consectetur ut sed est. Saepe error suscipit molestias. Exercitationem veniam quae est excepturi et vel esse. Sapiente quasi reiciendis consectetur.', '1983-05-02 03:31:15','1');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('27', '4', 'Libero vel nam ratione rerum ea.', 'Amet nemo ipsam ullam sint omnis velit rerum. Optio deserunt et est accusantium quis consequatur. Sit cum et facilis pariatur. A reiciendis qui beatae hic tempora magnam itaque.', '1984-07-17 00:29:24','2');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('28', '10', 'Sed voluptatem blanditiis a exercitationem tempora expedita.', 'Nostrum repudiandae voluptas commodi et sint et necessitatibus sit. Id omnis quos nemo optio aliquid. Odio nulla unde suscipit.', '2003-10-17 02:38:18','3');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('29', '7', 'Adipisci quos mollitia hic enim autem.', 'Nulla nobis magnam perspiciatis. Quae voluptas est sequi est veniam sed. Veniam ipsam nobis voluptatem animi amet eius. Dolor beatae deserunt mollitia.', '2011-08-05 05:48:17','1');
INSERT INTO forum_thread (id, topic_id, thread, content, created, creator_id) VALUES ('30', '7', 'Sunt quam asperiores qui aperiam ipsam odio accusantium et.', 'Assumenda omnis perspiciatis alias rerum labore. Temporibus sit quo fugit sed sapiente deserunt quam. Iure a sint quae optio et. Et nesciunt esse maxime esse ut enim quia.', '2009-03-02 19:29:09','2');

