# Generated by Django 4.2.1 on 2023-05-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_user_thread_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, default='Hello there', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.URLField(blank=True, default='https://t4.ftcdn.net/jpg/03/73/50/09/360_F_373500999_wAWkzJZRb2XHm9KeHEDcCJBkx4wR67us.jpg'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, default='user', max_length=16),
        ),
    ]
