# Generated by Django 4.2.1 on 2023-05-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_profile_about_profile_photo_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread',
            field=models.CharField(max_length=90, unique=True),
        ),
    ]
